# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#pr:
#  branches:
#    include:
#      - '*'  # must quote since "*" is a YAML reserved character; we want a string

pr: none

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: MyGitHub_splitman2run # The name used to reference this repository in the checkout step
      type: github
      endpoint: lezhumain
      name: lezhumain/SplitMan2-run

variables:
  - group: var_groupe
  - name: IMAGE
    value: splitman2api
  - name: SREPO
    value: SplitMan2-API

stages:
  - stage: Build
    jobs:
      - job: Build_Docker_Containers
        steps:
          - checkout: self
          - checkout: MyGitHub_splitman2run

          - script: |
              cd "$SREPO"
              echo "$HOST_IP" | wc
              bash ../SplitMan2-run/run_docker_e2e.sh "https" "$SREPO"
              docker save "$IMAGE" -o "$(Build.ArtifactStagingDirectory)/$IMAGE.tar"
            env:
              HOST_IP: $(DEBIAN_IP)
            displayName: 'Build containers'

          - publish: '$(Build.ArtifactStagingDirectory)/$(IMAGE).tar'
            displayName: 'Publish tar image'
            artifact: $(IMAGE)_tar
