# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [pull_request] 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy: 
      matrix:
        # see available versions here: https://github.com/actions/setup-java
        java-version: [12, 17]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Clean
      run: mvn clean

    - name: Validate
      run: mvn validate

    - name: Compile
      run: mvn compile
      
    - name: Compile Tests
      run: mvn compiler:testCompile
      
    - name: Test
      run: mvn test
